const SUBMIT_WISH_REQUEST = "SUBMIT_WISH_REQUEST";
const SUBMIT_WISH_SUCCESS = "SUBMIT_WISH_SUCCESS";
const SUBMIT_WISH_FAILURE = "SUBMIT_WISH_FAILURE";

const SUBMIT_WISH_OFFER_REQUEST = "SUBMIT_WISH_OFFER_REQUEST";
const SUBMIT_WISH_OFFER_SUCCESS = "SUBMIT_WISH_OFFER_SUCCESS";
const SUBMIT_WISH_OFFER_FAILURE = "SUBMIT_WISH_OFFER_FAILURE";
const SUBMIT_WISH_OFFER_CLEAR = "SUBMIT_WISH_OFFER_CLEAR";

const ACCEPT_OFFER_REQUEST = "ACCEPT_OFFER_REQUEST";
const ACCEPT_OFFER_SUCCESS = "ACCEPT_OFFER_SUCCESS";
const ACCEPT_OFFER_FAILURE = "ACCEPT_OFFER_FAILURE";

export default {
  SUBMIT_WISH_REQUEST,
  SUBMIT_WISH_SUCCESS,
  SUBMIT_WISH_FAILURE,
  SUBMIT_WISH_OFFER_REQUEST,
  SUBMIT_WISH_OFFER_SUCCESS,
  SUBMIT_WISH_OFFER_FAILURE,
  SUBMIT_WISH_OFFER_CLEAR,
  ACCEPT_OFFER_REQUEST,
  ACCEPT_OFFER_SUCCESS,
  ACCEPT_OFFER_FAILURE
};
