const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const CLEAN_LOGIN_ERROR = "CLEAN_LOGIN_ERROR";

const SIGNUP_REQUEST = "SIGNUP_REQUEST";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_FAILURE = "SIGNUP_FAILURE";

const SIGNOUT_REQUEST = "SIGNOUT_REQUEST";
const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
const SIGNOUT_FAILURE = "SIGNOUT_FAILURE";

export default {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  SIGNUP_FAILURE,
  SIGNOUT_REQUEST,
  SIGNOUT_SUCCESS,
  SIGNOUT_FAILURE,
  CLEAN_LOGIN_ERROR
};
