const SUBMIT_WISH_REQUEST = "SUBMIT_WISH_REQUEST";
const SUBMIT_WISH_SUCCESS = "SUBMIT_WISH_SUCCESS";
const SUBMIT_WISH_FAILURE = "SUBMIT_WISH_FAILURE";

export default {
  SUBMIT_WISH_REQUEST,
  SUBMIT_WISH_SUCCESS,
  SUBMIT_WISH_FAILURE
};
