const CANCEL_WISH_REQUEST = "CANCEL_WISH_REQUEST";
const CANCEL_WISH_SUCCESS = "CANCEL_WISH_SUCCESS";
const CANCEL_WISH_FAILURE = "CANCEL_WISH_FAILURE";

export default {
  CANCEL_WISH_REQUEST,
  CANCEL_WISH_SUCCESS,
  CANCEL_WISH_FAILURE,
};
